### ISSUE TITLE
Support for PyTorch 1.7?

### ISSUE THREAD

**Issue by listener17** [IntelLabs/distiller#551]
I saw Distiller was tested with PyTorch 1.3.

Are there any plans to move Distiller to support PyTorch 1.7?

**Comment by ashutoshmishra1014** [comment]
Updating distiller pytorch version to 1.5 or above just breaks distiller beyond repair by simple tweaks.
This could be because of the pytorch internals heavily used within the distiller especially around onnx and jit usage for pytorch graph parsing purposes.
@guyjacob Can you please comment on this issue or if there is any plans to maintain the distiller repository on a frequent basis , to support later versions of pytorch ?

**Comment by guyjacob** [comment]
Hi @ashutoshmishra1014, @listener17,

Indeed the last officially supported PyTorch version in Distiller is 1.3.1. At the moment we don't have plans to update it to support later versions.

You might want to take a look at @rotx-maxim's fork here:
https://github.com/MaximIntegratedAI/distiller
It appears he added PyTorch 1.5 support there, and even working on PyTorch 1.7 support in a branch.
(there's also an open PR here - #518 - but it looks like the fork I just mentioned is in a more mature state)

**Comment by TigerVersusT** [comment]
> Hi @ashutoshmishra1014, @listener17,
> 
> Indeed the last officially supported PyTorch version in Distiller is 1.3.1. At the moment we don't have plans to update it to support later versions.
> 
> You might want to take a look at @rotx-maxim's fork here: https://github.com/MaximIntegratedAI/distiller It appears he added PyTorch 1.5 support there, and even working on PyTorch 1.7 support in a branch. (there's also an open PR here - #518 - but it looks like the fork I just mentioned is in a more mature state)

Thanks for your information, I've tried out the latest 1.7 branch you mentioned, actually it is not fully supportted, for example the command "--export to onnx" and "--thinify". Looks like I have to read and write these commands myself.
